import karupattiCardImage from "../features/image/karupattiCardImage.png";
import DiscountNewImage from "../features/image/DiscountNewImage.png";
import LeafImage from "../features/image/LeafImage.png";
import RateingKarupatti from "../features/image/RateingKarupatti.png";
import LikeHeart from "../features/image/LikeHeart.png";
import coconutoilLarge from "../features/image/coconutoilLarge.png";
import healthmixLarge from "../features/image/healthmixLarge.png";
import riceWoodLarge from "../features/image/riceWoodLarge.png";
import DiscountRice from "../features/image/DiscountRice.png";
import DiscountOil from "../features/image/DiscountOil.png";
import groungnutoilNaturalpage from "../features/image/groungnutoilNaturalpage.png";
import gingellyoilNatiral from "../features/image/gingellyoilNatiral.png";
import rawRiceStoreLarge from "../features/image/rawRiceStoreLarge.png";
// import coldPressedGroundnutOIlNatural from "../features/image/coldPressedGroundnutOIlNatural.jpg";
export const cardDatas = [
  {
    DiscountNewImage: DiscountNewImage,
    LeafImage: LeafImage,
    karupattiLargeImage: karupattiCardImage,
    RateingKarupatti: RateingKarupatti,
    Rating: "200 ratings",
    Hearts: LikeHeart,
    name: "Karupatti (Palm Jaggery) – 1 Kg",
    price: 420,
    oldPrice: 420,
  },
  {
    DiscountNewImage: DiscountRice,
    LeafImage: LeafImage,
    karupattiLargeImage: riceWoodLarge,
    RateingKarupatti: RateingKarupatti,
    Rating: "1078 ratings",
    Hearts: LikeHeart,
    name: "Rice  90, 5 kg",
    price: 420,
    oldPrice: 420,
  },
  {
    DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: coconutoilLarge,
    RateingKarupatti: RateingKarupatti,
    Hearts: LikeHeart,
    Rating: "782 ratings",
    name: "Cold pressed oil  – 500 Ml",
    price: 420,
    oldPrice: 420,
  },
  {
    DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: healthmixLarge,
    RateingKarupatti: RateingKarupatti,
    Rating: "41 ratings",
    Hearts: LikeHeart,
    name: "Health mix  – 500 Gms",
    price: 420,
    oldPrice: 420,
  },
];

export const naturalOilDatas = [
  {
    DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: coconutoilLarge,
    RateingKarupatti: RateingKarupatti,
    Rating: "782 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Coconut Oil – 500 Ml",
    price: 160,
    oldPrice: 200,
  },
  {
    // DiscountNewImage: DiscountRice,
    LeafImage: LeafImage,
    karupattiLargeImage: groungnutoilNaturalpage,
    RateingKarupatti: RateingKarupatti,
    Rating: "30 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Coconut Oil – 500 Ml",
    price: 120,
    oldPrice: 150,
  },
  {
    DiscountNewImage: DiscountNewImage,
    LeafImage: LeafImage,
    karupattiLargeImage: gingellyoilNatiral,
    RateingKarupatti: RateingKarupatti,
    Hearts: LikeHeart,
    Rating: "9 ratings",
    name: "Gingelly oil – 250 Ml",
    price: 80,
    oldPrice: 90,
  },
  {
    DiscountNewImage: DiscountNewImage,
    LeafImage: LeafImage,
    karupattiLargeImage: groungnutoilNaturalpage,
    RateingKarupatti: RateingKarupatti,
    Rating: "3 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Groundnut Oil – 1L",
    price: 240,
    oldPrice: 300,
  },
];

export const belowStoreDatas = [
  {
    // DiscountNewImage: DiscountNewImage,
    LeafImage: LeafImage,
    karupattiLargeImage: healthmixLarge,
    RateingKarupatti: RateingKarupatti,
    Rating: "782 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Coconut Oil – 500 Ml",
    price: 160,
    oldPrice: 200,
  },
  {
    DiscountNewImage: DiscountRice,
    LeafImage: LeafImage,
    karupattiLargeImage: rawRiceStoreLarge,
    RateingKarupatti: RateingKarupatti,
    Rating: "30 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Coconut Oil – 500 Ml",
    price: 120,
    oldPrice: 150,
  },
  {
    DiscountNewImage: DiscountNewImage,
    LeafImage: LeafImage,
    karupattiLargeImage: karupattiCardImage,
    RateingKarupatti: RateingKarupatti,
    Hearts: LikeHeart,
    Rating: "9 ratings",
    name: "Gingelly oil – 250 Ml",
    price: 80,
    oldPrice: 90,
  },
  {
    DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: groungnutoilNaturalpage,
    RateingKarupatti: RateingKarupatti,
    Rating: "3 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Groundnut Oil – 1L",
    price: 240,
    oldPrice: 300,
  },
];

export const coldPressedOillDatas = [
  {
    DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: gingellyoilNatiral,
    RateingKarupatti: RateingKarupatti,
    Rating: "782 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Coconut Oil – 500 Ml",
    price: 160,
    oldPrice: 200,
  },
  {
    DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: coconutoilLarge,
    RateingKarupatti: RateingKarupatti,
    Rating: "30 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Coconut Oil – 500 Ml",
    price: 120,
    oldPrice: 150,
  },
  {
    DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: groungnutoilNaturalpage,
    RateingKarupatti: RateingKarupatti,
    Hearts: LikeHeart,
    Rating: "9 ratings",
    name: "Gingelly oil – 250 Ml",
    price: 80,
    oldPrice: 90,
  },
  {
    // DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: gingellyoilNatiral,
    RateingKarupatti: RateingKarupatti,
    Rating: "3 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Groundnut Oil – 1L",
    price: 240,
    oldPrice: 300,
  },
  {
    // DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: coconutoilLarge,
    RateingKarupatti: RateingKarupatti,
    Hearts: LikeHeart,
    Rating: "9 ratings",
    name: "Gingelly oil – 250 Ml",
    price: 80,
    oldPrice: 90,
  },
  {
    DiscountNewImage: DiscountNewImage,
    LeafImage: LeafImage,
    karupattiLargeImage: groungnutoilNaturalpage,
    RateingKarupatti: RateingKarupatti,
    Rating: "3 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Groundnut Oil – 1L",
    price: 240,
    oldPrice: 300,
  },
];

export const SuggestedProductsData = [
  {
    // DiscountNewImage: DiscountNewImage,
    LeafImage: LeafImage,
    karupattiLargeImage: healthmixLarge,
    RateingKarupatti: RateingKarupatti,
    Rating: "782 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Coconut Oil – 500 Ml",
    price: 160,
    oldPrice: 200,
  },
  {
    DiscountNewImage: DiscountRice,
    LeafImage: LeafImage,
    karupattiLargeImage: rawRiceStoreLarge,
    RateingKarupatti: RateingKarupatti,
    Rating: "30 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Coconut Oil – 500 Ml",
    price: 120,
    oldPrice: 150,
  },
  {
    DiscountNewImage: DiscountNewImage,
    LeafImage: LeafImage,
    karupattiLargeImage: karupattiCardImage,
    RateingKarupatti: RateingKarupatti,
    Hearts: LikeHeart,
    Rating: "9 ratings",
    name: "Gingelly oil – 250 Ml",
    price: 80,
    oldPrice: 90,
  },
  {
    DiscountNewImage: DiscountOil,
    LeafImage: LeafImage,
    karupattiLargeImage: groungnutoilNaturalpage,
    RateingKarupatti: RateingKarupatti,
    Rating: "3 ratings",
    Hearts: LikeHeart,
    name: "Cold Pressed Groundnut Oil – 1L",
    price: 240,
    oldPrice: 300,
  },
];
